### ISSUE TITLE
Fruit Trees decay into regular trees

### ISSUE THREAD

**Issue by Ladysarajane** [teagan75/Metamorphoses-2#3] opened 2020-05-28 13:22 UTC
I got two plum trees and planted one. Had fruit for a few days...then all the fruit disappeared.

I had an apple tree too. (I got lucky and found 8 apples in one of Yuliffs chests in his house I made an apple tree and planted it. It was a nice apple tree...but like the plum..fruit one day disappeared, just leaving a plain oak tree. I made another sapling of each from fruits I had picked and planted those. Plum tree had already decayed into oak tree. Apple tree hanging on for now. 
![2020-05-28_09 03 55](https://user-images.githubusercontent.com/34258851/83146711-b2155c80-a0c4-11ea-8039-6bdf4f6b825a.png)

Also what quest gives us spruce saplings? 
The Apprentice Builder and the poultry farm gave me Jungle saplings as rewards, but I haven't had a spruce tree yet. I just got to the chicken coop and thought about it. Not a big deal I can buy one from the General Store.

**Comment by teagan75** [comment] 2020-05-28 13:53
> Also what quest gives us spruce saplings?
> The Apprentice Builder and the poultry farm gave me Jungle saplings as rewards, but I haven't had a spruce tree yet. I just got to the chicken coop and thought about it. Not a big deal I can buy one from the General Store.

I don't have a quest that gives spruce saplings. I could change the reward for the lumberjack to give two spruce saplings instead of two iron axes.

**Comment by teagan75** [comment] 2020-05-28 13:54
> I got two plum trees and planted one. Had fruit for a few days...then all the fruit disappeared.
> 
> I had an apple tree too. (I got lucky and found 8 apples in one of Yuliffs chests in his house I made an apple tree and planted it. It was a nice apple tree...but like the plum..fruit one day disappeared, just leaving a plain oak tree. I made another sapling of each from fruits I had picked and planted those. Plum tree had already decayed into oak tree. Apple tree hanging on for now.

Weird stuff happening this time around. I will see what I can do about it because it is important they stay fruit trees.

**Comment by Ladysarajane** [comment] 2020-05-28 14:06
It seems that once you pick a fruit it disappears entirely...One time shot on fruit trees. If you get a tree with only 2 fruits...you cannot make another tree or use that tree for eating at all. 

Also worms...before you only get them from Johan in the park...this time hoeing dirt is giving me them when hoeing my garden.

**Comment by teagan75** [comment] 2020-05-28 14:10
> It seems that once you pick a fruit it disappears entirely...One time shot on fruit trees. If you get a tree with only 2 fruits...you cannot make another tree or use that tree for eating at all.

It might be dynamic trees interfering with the fruit trees. I just found the config that disables the apple drops from oak trees. I can re-enable that or maybe just get rid of the mod entirely. I will test it. I thought it would be cool to have unique trees but not at the expense of food lol.



> Also worms...before you only get them from Johan in the park...this time hoeing dirt is giving me them when hoeing my garden.

Ah i forgot to change that config

**Comment by teagan75** [comment] 2020-05-28 14:21
From the Dynamic Trees Harvestcraft compat site " Fruit trees will have normal Pam's Harvestcraft fruit blocks.  These will break completely when harvested but the parent tree will reproduce the fruit on the tree at random locations.  The fruit removal is NOT A BUG.  DO NOT REPORT THIS AS A BUG EITHER HERE OR TO THE PAM'S HARVESTCRAFT PROJECT.  This was done to make the fruit growing process more realistic."

**Comment by Ladysarajane** [comment] 2020-05-28 14:38
Ah....I forgot dynamic trees was in here. Okay...both of my trees is bare...lets see how long it takes for them to regrow.

**Comment by teagan75** [comment] 2020-05-28 14:42
I am doing the same. I included Dynamic Trees but I am not forcing it. There isn't a way to disable the fruit dynamics so I just put a note in the quest book.

Edit: If it takes too long I can always get rid of the Dynamic HC compat mod

**Comment by Ladysarajane** [comment] 2020-05-28 15:06
Uh...if we have dynamic trees...shouldn't the trees be rounded with branches and drop seeds instead of saplings?

**Comment by teagan75** [comment] 2020-05-28 15:07
Only if you use the seed for Dynamic Trees. I didn't disable vanilla-ish trees because dynamic trees take forever to grow. I may just need to get rid of the HC dynamic compat mod

**Comment by Ladysarajane** [comment] 2020-05-28 15:17
Yeah...as of yet...5 in game days...and no fruit regrowth

**Comment by teagan75** [comment] 2020-05-28 15:19
Me too. I will get rid of it. Cannot afford to have time longer and no ability to bonemeal

**Comment by teagan75** [comment] 2020-05-28 15:28
btw, thank you for helping me test the mods. It will help get this pack to release state quicker 😸

**Comment by Ladysarajane** [comment] 2020-05-28 15:32
No...problem as long as you don't mind my "complaints"  🤣 
I am disabled and stuck at home especially with this stuff..since I am "immune compromised"
This really helps me keep busy...LOVE the testing.

**Comment by teagan75** [comment] 2020-05-28 19:54
These issues should be resolved in v0.3_beta

**Closed as completed by teagan75** 2020-05-28 19:54 UTC
