### ISSUE TITLE
City quest/ Runic shears

### ISSUE THREAD

**Issue by DodgerWoman26** [teagan75/Metamorphoses-2#29] opened 2020-11-24 01:09 UTC
HI! I want to say I am excited to play this again, and so far it has been awesome how smoothly everything works. Minus the usual Harvest issues lol. I have gotten into City- and ran into the first issue so far. The runic shears quest asks you to craft and use the shears to obtain wildewheat, spirit herb and fey leather. The fey leather was no problem but I tried and can not get anything using the shears on wheat and beets. Perhaps it's because you have to grow the harvest festival crops and can't plant the normal seeds? Or maybe I am missing something  ;) But it won't work on the wheat at all, and right clicking the beets only gives me beets- and I have tried A LOT- thinking perhaps it was just a ratio drop.

**Comment by Ladysarajane** [comment] 2020-11-24 14:34
Hi DodgerWoman26! How did you make the runic shears? I can only obtain the pam's harvestcraft beets and that will not work in the ritual. Where did you find the minecraft beets? In testing I did give myself a beet in my test world and I made the shears The fey leather is easy, but as you stated the shears will not work on Harvest craft wheat, nor can I make the spirit herb with the shears. Need Jakob to turn some pam's beets into minecraft beets and harvest craft wheat into regular wheat. (suggestion)

**Comment by DodgerWoman26** [comment] 2020-11-24 16:15
Hi Ladysarajane! At first I was trying to be clever and tried using the transmutation ritual to get reg carrots and beets for my tek ppl. It's such a pain getting emeralds if all you can really sell is their wood lol. However cocoa into carrots worked, but you have to have full grown carrots to turn into beets- the harvest ones did not work. So when I could finally grow beets from harvest festival I tried them. They did work in the ritual to make the shears for me. They look the same, but tek ppl still won't harvest them. How does Jakob turn beets and wheat into reg version? That's the fish guy right lol. I'm kinda stuck at this point. Not enough emeralds to continue with tek line and can't get the spirit herb and the wildewheat. BTW Harvest festival beets opened in Autumn 3rd year for me- not sure if it's a year or selling crops unlock.

**Comment by Ladysarajane** [comment] 2020-11-24 16:26
I was suggesting that maybe Teagan could have an exchange set up with Jakob to exchange the beets and wheat for minecraft ones like he does with Harvest festival milk, eggs and wool. I am only in summer ....and maybe I have the wrong name...I meant for the park person to exchange them.  I am currently in Summer of my 3rd year in my test world...so no beets yet. My test world was made previously  a few months ago. My current world, I am in Summer of year one.

**Comment by DodgerWoman26** [comment] 2020-11-24 16:51
Oh ok. Got it. Ya, trading with the Johan (park guy, you were close lol) would be a great idea. I have not yet found another alternative. Unless the quest changes to getting the leather, and the other two as a reward in seed form or something....

**Comment by teagan75** [comment] 2020-11-24 17:10
Thank you both for bringing up an issue and for the suggestions. I will be making the changes hopefully this week. I haven’t had the chance to thoroughly test the City chapter.

**Comment by Ladysarajane** [comment] 2020-11-24 17:15
> Thank you both for bringing up an issue and for the suggestions. I will be making the changes hopefully this week. I haven’t had the chance to thoroughly test the City chapter.

Thanks Teagan...not sure how easy it will be to update with curse merging with Overwolf. Things seem to be a mess there for now.  Quick question...did you add actually addition seeds to the composter? I have a ton of flax and rice seeds and cannot get rid of them. I cannot remember if that was one of the changes you were going to make or not.

**Comment by DodgerWoman26** [comment] 2020-11-24 17:44
Thanks Teagan!! I really am enjoying the pack. Looking forward to actually completing it and not rage quitting lol. This was really the first actual issue I ran into, so you have done a great job so far! @Ladysarajane I have been able to put my rice seeds into the composter, but the actual worker never seems to do it themselves, so I just manually do it every once in awhile. I don't know about flax, as I have been sticking to mostly rice and oats.

**Comment by teagan75** [comment] 2020-11-24 18:26
hmm the composter should compost any item that is ore dict seed

**Comment by Ladysarajane** [comment] 2020-11-24 19:16
> hmm the composter should compost any item that is ore dict seed

This is not the minecolonies composter, it is the composter for the quest in the beginning quest that we had to make. It doesn't accept the Actually additions seeds. Not sure why it is doing this. So far my composter hasn't disappeared in this playthrough like it did before. So that is good. 

Edit...it is the Canny Composter that is not accepting the seeds and I think it is the meta data doing it since the seeds have "leveled" up with agricraft.

**Comment by teagan75** [comment] 2020-12-02 21:42
So, I have been fighting with the runic shears all day lol. I think I have acceptable scripts in place now:

I have changed the pyre ritual for pereskia to use Pam's beets. Tested and it works. 
I have added the ability to shear a wheat block to get 9 wildewheat. 
I have added the ability to shear harvest festival herbs (chamomile, lavender and mint) to get spirit herbs. Those seem to grow frequently. Also you can make seeds to grow the Roots plants.

**Comment by teagan75** [comment] 2020-12-02 22:08
FYI I cannot update the pack right now. The function has been removed from Twitch but not ready yet on Overwolf

**Comment by Ladysarajane** [comment] 2020-12-02 22:29
> FYI I cannot update the pack right now. The function has been removed from Twitch but not ready yet on Overwolf

Yeah.....I didn't think you would have a good time with Overwolf on updating. I think they were hoping to be up and running on Nov30, but that didn't happen.

**Comment by DodgerWoman26** [comment] 2020-12-03 00:03
Well that stinks- for everyone involved lol. Hopefully they can add the function soon!

**Comment by teagan75** [comment] 2020-12-03 22:07
I can put the files here on github if you guys know how to manually update
your packs

**Comment by Ladysarajane** [comment] 2020-12-03 22:51
I think I remember how to do it. I'll give it a go.

I think overwolf is suppose to link now to github too now for installing. I'll give it a go at it to see how Overwolf acts.

**Comment by DodgerWoman26** [comment] 2020-12-04 04:06
I don't think I am that savvy- never done it before lol

**Comment by Ladysarajane** [comment] 2020-12-04 14:03
@DodgerWoman26, most of it should be just copying and pasting in the correct folder structure. It will depend on how Teagan presents it to us. She may have the whole game and all we have to do is copy and paste the whole file over the old one, overwriting all old folders (except save folder and the journey map folder (unless you haven't set any waypoints)....or she just may give us the changed files and config changes to copy and paste in the correct folder spots. Just copy and paste the whole Modpack folder somewhere safe as backup before trying the changes. I can try to help you here once Teagan gives us the changes and see if I can upgrade mine and give you instructions how I did it. 😸

**Comment by teagan75** [comment] 2020-12-04 17:43
https://github.com/teagan75/Metamorphoses-2/releases/tag/0.6.5.4

**Comment by Ladysarajane** [comment] 2020-12-04 18:12
I have downloaded it, but not unzipped yet. Have to finish teaching...(coach for my 7yo niece) virtual homeschooling. I will play with it later this evening.

**Comment by DodgerWoman26** [comment] 2020-12-04 18:24
@Ladysarajane I might be able to figure it out with instructions lol, I know basics- just not confident because I have never done a whole update manually.

**Comment by teagan75** [comment] 2020-12-04 19:21
there are three dots in the upper right corner of the instance in the curse launcher that gives you the option to open the folder. Inside are all the folders needed to run your game. In the above zip file are the folders that need to overwrite the folders in your instance.

**Comment by Ladysarajane** [comment] 2020-12-05 00:31
Unfortunately just unzipping and copying into the instance causes the startup to have a failure. I backed up my save and journeymap folder and attempted a brand new instance and copying the new files and it still failed on startup. So I deleted that instance. I downloaded the instance again (old files) and copied those to the custom profile. After those were copied, I then copied and pasted the new files. I added back in my backup files (my saves and journeymap files) and attempted a start up. I ran the game without problems, but even with me running the quest to reload the quest book...it doesn't look updated to me. So I am not sure if the new files actually did anything. Still investigating....options on this. I may need to start a new world to see if there are any changes. @teagan75 did you update the fey crafter reward? (so I can gauge if the new world has updated early. Also the turnip quest?)

I'm heading to bed early. They make kids do so much in 2nd grade. Gives us adults a headache trying to help them...lol!

**Comment by teagan75** [comment] 2020-12-05 13:44
you know I didn't change the fey award because I couldn't think of a
suitable award but the turnip quest should be gone. It is weird that it is
causing issues. I can try uploading again

**Comment by Ladysarajane** [comment] 2020-12-05 14:09
No....I don't think this is a problem with the files...I think this is with Overwolf. I copied and pasted the same files into the same set of files from instance that I downloaded and then pasted into a custom instance. The files are identical...so why would one run and the other give a fatal error and fail to load? As to the quest book not updating...that may be me. I was looking at the fey quest. I really didn't look at the turnip quest. Let me play with the instances some more and this time I will paste the log when I get the fatal error to see what you can make of it before you upload the files again. My brain wasn't firing on all thrusters last evening with that headache and I know I might have missed something.

**Comment by Ladysarajane** [comment] 2020-12-05 15:15
Okay....I tried a new world with the fresh files....The questing book was still not updated...had the turnip quest still, so I attempted to copy and paste the new files again to see if my previous download was faulty. Went to load it up again and received that error. 
[latest.log](https://github.com/teagan75/Metamorphoses-2/files/5647275/latest.log)


Is this error related to astral sorcery?

**Comment by teagan75** [comment] 2020-12-10 15:13
Looks like a launcher issue actually. But good news I have just had it confirmed that the ability to update modpacks will return and hopefully soon!

**Comment by Ladysarajane** [comment] 2020-12-10 15:23
Thats good. I hope their definition of soon is the same as mine! 😆

**Comment by DodgerWoman26** [comment] 2020-12-10 16:55
Glad to hear it! Looking forward to being able to play the pack again lol. I also hope it doesn't take too long ;)

**Comment by teagan75** [comment] 2020-12-14 16:58
export function is back so I will be working on an update today

**Comment by Ladysarajane** [comment] 2020-12-14 18:19
Looking forward to it 😄

**Comment by Ladysarajane** [comment] 2020-12-22 18:50
Still no luck updating? Now that school is no longer in, I have more free time to play. Don't forget to add Aubergine seeds to the General Store. Wow! Modii had the luck getting Termite clay. I don't think I have ever come across that clay in my worlds.  Am I able to make a termite mound with a termite?

**Comment by teagan75** [comment] 2020-12-22 20:02
You may. I haven’t tried making a termite mound. 

I have been having issues updating. Seems the export is a bit buggy but I think I have settled it. I will make sure to add the Auvergne seeds before trying again. Hopefully it will upload tonight 😊

Edit: If I can get it up tonight, please let me know if there are any missing ids and blocks. It seems Curse didnt properly move or recognize some mods

**Comment by Ladysarajane** [comment] 2020-12-22 20:23
I will let you know.  Yeah, I think some people haven't updated their log in credentials with Overwolf and I think that the mods are not in the database. I know I come across some as "abandoned" and when I research the mod, The mod is in the database, but the author is not listed. 

Edit- I couldn't find the different versions on Metamorphosis 2. I had to edit the profile and uncheck the Manage Content. Then the button for different versions showed. Just in case people ask about the updating.

**Comment by teagan75** [comment] 2020-12-23 19:48
this issue should be fixed in v0.6.5.4

**Closed as completed by teagan75** 2020-12-23 19:48 UTC
